ALTER TABLE cust_trade_eris MODIFY (TYP_NAT_RISQUE_CODE DEFAULT ' ');

update cust_trade_eris set TYP_NAT_RISQUE_CODE = ' ' where TYP_NAT_RISQUE_CODE is null;
COMMIT;

ALTER TABLE GEM.CUST_TRADE_ERIS DROP CONSTRAINT PK_CUST_TRADE_ERIS;
ALTER TABLE GEM.CUST_TRADE_ERIS ADD (
CONSTRAINT PK_CUST_TRADE_ERIS
PRIMARY KEY
(PARTITION_KEY, CONTRAT_CODE, NAT_RISQUE_CODE, DEV_ORIG_CODE, APPLI_CODE, RAF_CODE, RAF_EMPRUNT_CODE, TYP_NAT_RISQUE_CODE)
USING INDEX LOCAL);

ALTER TABLE CUST_REFACTION DROP CONSTRAINT PK_CUST_REFACTION;
CREATE INDEX GEM.I1_CUST_REFACTION ON GEM.CUST_REFACTION
(PARTITION_KEY, ATTRIBUTE_VALUE_1, ATTRIBUTE_VALUE_2, ATTRIBUTE_VALUE_3, PERIMETRE_CODE, STATISTIQUE_CODE, METHODE_CALCUL, NOM_COURBE,PROXY_SN,SCORE, cutoff);
