#! /bin/ksh

set -x 

OUTPUT_FILE=/home/alozahic/exploit/systeme/suivi/ABSYSS_CENTOS/SURVEILLANCE_PROD_544/COLOR/VTOM.html 

case $# in
  0) DATE_D=$(date +"%Y-%m-%d"); DATE_F=$DATE_D; CLAUSE="vtexpdatevalue = CURRENT_DATE";;
  1) DATE_D=$1; DATE_F=$DATE_D; CLAUSE="vtexpdatevalue = cast ('$DATE_D' as date)";;
  2) DATE_D=$1; DATE_F=$2; CLAUSE="vtexpdatevalue >= cast ('$DATE_D' as date) AND vtexpdatevalue <= cast ('$DATE_F' as date)";;
  *) echo "Nombre d'arguments incorrect"; exit 1;;
esac

echo ' <html>
     <head>
  <title></title>
  <style type="text/css">
  body {
    color: black;
    background-color: #000000}
  </style>
</head> 
<table border="1">
  <tr bgcolor="#00BFFF"> ' > /home/alozahic/exploit/systeme/suivi/ABSYSS_CENTOS/SURVEILLANCE_PROD_544/COLOR/VTOM.html

$TOM_HOME/sgbd/bin/psql -A -H -c "SELECT vtenvname, vtapplname, vtjobname, vtbegin, vtend, vtend - vtbegin, vtexpdatevalue, vtnbretry, vtretcode, vterrmess FROM vt_stats_job WHERE vtexpdatevalue=CURRENT_DATE AND vtjobname IS NOT NULL AND vtstatus=3 ORDER BY vtend ASC" -d vtom -h centos63 -p 33909 -U vtom >> /home/alozahic/exploit/systeme/suivi/ABSYSS_CENTOS/SURVEILLANCE_PROD_544/COLOR/VTOM.html

NB_TEST=$(grep ";0;" $OUTPUT_FILE|wc -l)
echo $NB_TEST

#cat $OUTPUT_FILE | sed 12d | sed 's/<tr valign="top"/<tr valign="top" bgcolor=yellow/g' |  grep -v "<tr>" > $OUTPUT_FILE
cat $OUTPUT_FILE | sed 12d | sed '/<tr valign="top"/d' |  grep -v "<tr>" > $OUTPUT_FILE

if [ `/bin/grep GLISSE $OUTPUT_FILE | wc -l` -ne 0 ] 
then 
sed -i "/GLISSE/i <tr valign="top" bgcolor=deeppink>" $OUTPUT_FILE 
	else 
		if [ `/bin/grep SURVEIL $OUTPUT_FILE | wc -l` -ne 0 ] 
		then
		sed -i "/SURVEIL/i <tr valign="top" bgcolor=#FFFF00>" $OUTPUT_FILE 
			else
				if [ `/bin/grep PRODUCTION $OUTPUT_FILE | wc -l` -ne 0 ]
				then
				sed -i "/PRODUCTION/i <tr valign="top" bgcolor=#FF0000>" $OUTPUT_FILE 
else 
if [ `/bin/grep PERL $OUTPUT_FILE | wc -l` -ne 0 ]
then
sed -i "/PERL/i <tr valign="top" bgcolor=#0000FF>" $OUTPUT_FILE 
	else
		if [ `/bin/grep TSEND $OUTPUT_FILE | wc -l` -ne 0 ]
		then
		sed -i "/TSEND/i <tr valign="top" bgcolor=#FFA500>" $OUTPUT_FILE 
			else
				if [ `/bin/grep XLIENS $OUTPUT_FILE | wc -l` -ne 0 ]
				then
				sed -i "/XLIENS/i <tr valign="top" bgcolor=#8A2BE2>" $OUTPUT_FILE 
fi
		fi
				fi
fi
		fi
				fi

NB_TEST=$(grep ";0;" $OUTPUT_FILE|wc -l)

tmail -se "arnaud.lozahic@absyss.com" -to "arnaud.lozahic@absyss.com" -smtp "jupiter" -sub "[ARNAUD_TERMINE] ($NB_TEST)" -msg "Statistiques du $DATE_D au $DATE_F extraites le $(date +'%d/%m/%Y a %H:%M')" -att "$OUTPUT_FILE" -msgf "$OUTPUT_FILE"
