#! /bin/ksh

set -x

OUTPUT_FILE=/exploit/systeme/suivi/HTML/Erreurs_VTOM_RECETTE.html 

case $# in
  0) DATE_D=$(date +"%Y-%m-%d"); DATE_F=$DATE_D; CLAUSE="vtexpdatevalue = CURRENT_DATE";;
  1) DATE_D=$1; DATE_F=$DATE_D; CLAUSE="vtexpdatevalue = cast ('$DATE_D' as date)";;
  2) DATE_D=$1; DATE_F=$2; CLAUSE="vtexpdatevalue >= cast ('$DATE_D' as date) AND vtexpdatevalue <= cast ('$DATE_F' as date)";;
  *) echo "Nombre d'arguments incorrect"; exit 1;;
esac

echo ' <html>
     <head>
  <title></title>
<style type="text/css">
body {
font-family: Verdana; 
font-size: 12px; 
margin: 0; 
padding: 0; 
background-image: url('/exploit/systeme/suivi/1.jpg');
background-color: yellow;
color: black;
</style>
     </head> ' > $OUTPUT_FILE

/produit/vtom/v52/sgbd/bin/psql -A -H -c "SELECT vtenvname, vtapplname, vtjobname, vtbegin, vtend, vtend - vtbegin, vtexpdatevalue, vtnbretry, 'EN-ERREUR', vtretcode, vterrmess FROM vt_stats_job WHERE $CLAUSE AND vtjobname IS NOT NULL AND vtstatus = 4 ORDER BY vtend ASC" -d vtom -h localhost -p 30009 -U vtom >> $OUTPUT_FILE

NB_TEST=$(grep "EN-ERREUR" $OUTPUT_FILE|wc -l)

/exploit/batch/sendmime.sh -s "[VTOM RECETTE] Erreurs ($NB_TEST)" -t "Statistiques du $DATE_D au $DATE_F extraites le $(date +'%d/%m/%Y a %H:%M')" arnaud.lozahic@mondial-assistance.fr $OUTPUT_FILE 
