#!/bin/ksh

FIC_LOG=$TOTO/DF/surveil_df.log

df -h | grep -v on | grep -v tmpfs | grep -v CentOS_6.3_Final | printf "%-30s %+15s %+15s %+15s %+10s %+10s \n" $(cut -f1) $(cut -f2) $(cut -f3) $(cut -f4) $(cut -f5) | awk '{print $5}' | sed 's/%//g' > $FIC_LOG
#df=`df -h | grep -v on | grep -v tmpfs | grep -v CentOS_6.3_Final | printf "%-30s %+15s %+15s %+15s %+10s %+10s \n" $(cut -f1) $(cut -f2) $(cut -f3) $(cut -f4) $(cut -f5) | awk '{print $5}' | sed 's/%//g'` 

#Reference: df
#echo $df | while read percent fs
for i in $FIC_LOG
do
#If Disk Usage increases above 90% send an email.
if [ $i -ge 90 ];
then
stop_moteurs SURVEIL
tmail -se "arnaud.lozahic@absyss.com" -to "arnaud.lozahic@absyss.com" -smtp "jupiter" -sub "URGENT Espace FS > 90% : CENTOS63" -msg "Surveillance FS extraite le $(date +'%d/%m/%Y a %H:%M')" -att "$FIC_LOG" -msgf "$FICLOG"
fi
done
