GLOBALES]
nbWaitRetry=2
StatusFailSubmit=AVENIR
StatusFailExist=ENCOURS
stats=1
AcceptOrItems=1
; timeBexist=120
; relanceAppCycliqueEnErreur=0
; relanceJobCycliqueEnErreur=0
; nbJoursRattrapage=2
; statusPileOne=1
; force_stats=0
; deplan_obj=0
; resnopla=0
; ManualRecovery=0
SecureEngineTimeout=600
delayHostVtSecure=300
blacklistCmd=/home4/alozahic/exploit/systeme/suivi/ABSYSS/BLACKLIST/Blacklist_mail.ksh

[TENGINE:PRODUCTION]
TRACE_LEVEL=3
TRACE_FILE=/home4/alozahic/Linux/avize/Ver544/traces/PRODUCTION.log
TRACE_FILE_SIZE=100
TRACE_FILE_COUNT=10
timeBexist=30
#secureEngineTimeout=600
#delayHostVtSecure=300
#blacklistCmd=/home4/alozahic/exploit/systeme/suivi/ABSYSS/BLACKLIST/Blacklist_mail.ksh

[TENGINE:SURVEIL]
TRACE_LEVEL=3
TRACE_FILE=/home4/alozahic/Linux/avize/Ver544/traces/SURVEIL.log
TRACE_FILE_SIZE=100
TRACE_FILE_COUNT=10
timeBexist=30
#SecureEngineTimeout=600
#delayHostVtSecure=300
#blacklistCmd=/home4/alozahic/exploit/systeme/suivi/ABSYSS/BLACKLIST/Blacklist_mail.ksh

[VTSERVER]
TRACE_LEVEL=3
TRACE_FILE=/home4/alozahic/Linux/avize/Ver544/traces/vtserver.log
TRACE_FILE_SIZE=40
TRACE_FILE_COUNT=5

[VTSGBD]
TRACE_LEVEL=3
TRACE_FILE=/home4/alozahic/Linux/avize/Ver544/traces/vtsgbd.log
TRACE_FILE_SIZE=40
TRACE_FILE_COUNT=5

[log]
appDisplayHeader=non
envDisplayHeader=non
tellFormat=non
tellClose=non
tellStatus=non
tellDate=non

[print]
appDisplayHeader=oui
envDisplayHeader=oui
tellFormat=oui
tellClose=oui
tellStatus=oui
tellDate=oui

[job]
tagScript=#

; [TRACES]
; mode=none
; family= A
; Level=D
; Directory=<monrepertoire>
; Filename=vtom.trc
; Filesize=10

; [VTOM_GCOS8]
; actif=1

; [VTOM_SNMP]
; actif=1
; agent=localhost

; [VTOM_PATROL]
; actif=1

; [CLUSTER]
; node1=1
; node2=1

[BDAEMON]
TRACE_LEVEL=6
TRACE_FILE=/home4/alozahic/Linux/avize/Ver544/traces/bdaemon.log
TRACE_FILE_SIZE=40
TRACE_FILE_COUNT=5

; [node1]
; ABM_LOGS=/tmp/

; [node2]
; ABM_LOGS=/tmp/

[TSNMP]
TRACE_LEVEL=1
TRACE_FILE=/home4/alozahic/Linux/avize/Ver544/traces/snmp.log
TRACE_FILE_SIZE=40
TRACE_FILE_COUNT=5

[VTOM_SNMP]
actif=1
agent=avize
